spring.application.name=backend


# Google Requirements
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=profile, email

# Stripe Requirements
stripe.api.secretKey=${STRIPE_SECRET_PKEY}

# URL Config
stripe.successUrl=http://localhost:4200/chat?payment=success
stripe.cancelUrl=http://localhost:4200/chat?payment=cancel

